/**
 * Fetch neighbourhood/suburb/quarter names from OpenStreetMap (same labels as the map tiles).
 * Writes packages/api/src/data/jordanOsmNeighborhoods.ts
 *
 *   npm run fetch:osm-jordan-areas -w @burqan/api
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { governorateForCoordinates } from "../utils/assignGovernorate.js";
import { MAIN_AREA_RADIUS_KM } from "../data/jordanAreaConstants.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, "../data/jordanOsmNeighborhoods.ts");

const OVERPASS = "https://overpass-api.de/api/interpreter";
const QUERY = `
[out:json][timeout:90];
area["ISO3166-1"="JO"][admin_level=2]->.jo;
(
  node["place"~"neighbourhood|suburb|quarter"](area.jo);
  way["place"~"neighbourhood|suburb|quarter"](area.jo);
);
out center;
`.trim();

type OsmEl = {
  tags?: Record<string, string>;
  center?: { lat: number; lon: number };
  lat?: number;
  lon?: number;
};

async function main() {
  const res = await fetch(OVERPASS, {
    method: "POST",
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      Accept: "application/json",
      "User-Agent": "BurqanStore/1.0 (fetch-osm-jordan-neighborhoods)",
    },
    body: `data=${encodeURIComponent(QUERY)}`,
  });
  if (!res.ok) throw new Error(`Overpass HTTP ${res.status}`);
  const data = (await res.json()) as { elements?: OsmEl[] };

  const byName = new Map<
    string,
    { name: string; governorate: string; centerLat: number; centerLng: number; radiusKm: number }
  >();

  for (const e of data.elements ?? []) {
    const tags = e.tags ?? {};
    const name = (tags["name:ar"] || tags.name || "").trim();
    if (!name || name.length < 2) continue;
    const lat = e.center?.lat ?? e.lat;
    const lng = e.center?.lon ?? e.lon;
    if (lat == null || lng == null) continue;

    const gov = governorateForCoordinates(lat, lng);
    const row = {
      name,
      governorate: gov,
      centerLat: lat,
      centerLng: lng,
      radiusKm: MAIN_AREA_RADIUS_KM,
    };
    const prev = byName.get(name);
    if (!prev) {
      byName.set(name, row);
      continue;
    }
    // Keep first; skip duplicate OSM name at different coords (rare)
  }

  const rows = [...byName.values()].sort((a, b) =>
    a.governorate.localeCompare(b.governorate, "ar") || a.name.localeCompare(b.name, "ar")
  );

  const lines = rows.map(
    (r) =>
      `  { name: ${JSON.stringify(r.name)}, governorate: ${JSON.stringify(r.governorate)}, centerLat: ${r.centerLat}, centerLng: ${r.centerLng}, radiusKm: ${r.radiusKm} },`
  );

  const ts = `/**
 * OpenStreetMap neighbourhood / suburb / quarter names in Jordan (Arabic).
 * Generated by: npm run fetch:osm-jordan-areas -w @burqan/api
 * Do not edit by hand — re-run the script to refresh from OSM.
 */
import type { JordanAreaSeed } from "./jordanDetailedAreas.js";

export const JORDAN_OSM_NEIGHBORHOODS: JordanAreaSeed[] = [
${lines.join("\n")}
];
`;

  writeFileSync(OUT, ts, "utf8");
  // eslint-disable-next-line no-console
  console.log(`Wrote ${rows.length} OSM neighborhoods → ${OUT}`);
}

main().catch((e) => {
  // eslint-disable-next-line no-console
  console.error(e);
  process.exit(1);
});
